port: 3000
debug: true
#Databse configs
database:
  postgres:
    driver: postgres
    database: test
    host: 127.0.0.1
    port: 2345
    user: postgres
    password: postgres
  mysql:
    driver: mysql
    database: database_name
    host: 127.0.0.1
    port: 3307
    user: postgres
    password: postgres
jwt:
  accessTTL: 86400
  refreshTTL: 864000